### ISSUE TITLE
Arkouda server version is out of date need a better way for this to be tracked automatically maybe?

### ISSUE THREAD

**Issue by mhmerrill** [mhmerrill/arkouda#150]

**Comment by reuster986** [comment]
One option, listed [here](https://packaging.python.org/guides/single-sourcing-package-version/) as choice 4, is to have a `VERSION` file in the top level directory that all code (e.g. `setup.py` and `arkouda_server.chpl`) reads from. I think I like this option the best, because it is language-agnostic.

However, we also need to choose a versioning scheme. Right now, we have a hybrid of semantic versioning (0.0.9) and date-based (2019.10.22), but we should probably go with one or the other. I lean towards date-based, because semantic is harder to agree on and we are still adding major functionality.

**Comment by BryantLam** [comment]
Semantic versioning does allow "whatever you want" if the Major Version  is less than 1.

Between semantic versioning and date-based, I'm okay with either. There are benefits for both.

**Comment by mhmerrill** [comment]
I believe this is addressed by #175
