### ISSUE TITLE
make the arkouda_server more robust to running out of memory

### ISSUE THREAD

**Issue by mhmerrill** [mhmerrill/arkouda#154]
Outline of what I think needs to be addressed to make the server more robust:
 * construct a `proc estFreeMem(): int` to return an estimate of remaining memory which could be allocated
 * for each message processing `proc fooMsg()` construct a proc to estimate the storage consumed during the operation based on the arguments and the algorithm to be used
 * for each message processing `proc fooMsg()` return an `"Error: operation would exceed memory available"` string if the operation would allocate (even temporarily) more memory than is available

**Comment by bradcray** [comment]
I don't know whether you're familiar with the Chapel memory module, but some of its routines _may_ be helpful here:  https://chapel-lang.org/docs/modules/standard/Memory.html#Memory.locale.physicalMemory

Note that while in HPC-world we're used to only dealing with physical memory, but in a portable setting, users may be more willing to use virtual memory as well.

@gbtitus, @ronawho: Related to this, Mike was curious whether there's a call that a Chapel user can make to ask how big the heap is?

**Comment by gbtitus** [comment]
> ... Mike was curious whether there's a call that a Chapel user can make to ask how big the heap is?

There is not.  We could add one, but we'd have to iterate on it to get it right.  The answer is easy if we're using a fixed heap, but that's not terribly common.  Otherwise, without registered memory we could check a variety of sources (system memory, `getrlimit()`, etc.) and find the most limiting value.  But with registered memory on an XC, depending on circumstances there are a number of things you can run out of first, so we would have to make and document some assumptions such as for example whether the answer should reflect allocating a single large object or many smaller ones.  But we could do it.

**Comment by gbtitus** [comment]
Does this issue at all provide any support for adding a feature to throw an error when an allocation fails, rather than killing the process?  Perhaps in specific circumstances?  We have talked now and then about doing this and always concluded that in general it seemed difficult because basically any expression and even many statements in Chapel can allocate.  But perhaps a restricted solution would still be possible and useful.

**Comment by mhmerrill** [comment]
I am thinking about adding a memory limit `config const perLocaleMemLimit` so we can set a limit memory usage to not exceed during server operations.

**Comment by mhmerrill** [comment]
I hooked the `st.addEntry()` procedure to catch most simple allocations into the symbol table. This should catch all the simple cases like binary operators and things that only allocate one new `pdarray`

**Comment by ronawho** [comment]
There is a runtime call `chpl_comm_regMemHeapInfo` that would give you the fixed heap size if there is one. If there is no fixed heap size (using dynamic registration or comm=none, size will be 0.)

You could do something like:

```chpl
use Memory;

extern proc chpl_comm_regMemHeapInfo(ref start: c_void_ptr, ref size: size_t):void;
var start: c_void_ptr, size: size_t;
chpl_comm_regMemHeapInfo(start, size);

var memLimit = if size > 0 then size:real else here.physicalMemory():real;

writeln(memLimit / (1024.0*1024.0*1024.0));
```

You should also be aware that functions like `memoryUsed()` require throwing `--memTracking`, which is very expensive. This has a huge impact on allocation time because allocation is serialized with a lock and we update a hash table. (This is because we typically use memory tracking to look for leaks so and we store metadata about allocations.)

There are 2 upstream issues that request faster versions of something like `memoryUsed()`
 - https://github.com/chapel-lang/chapel/issues/10396
 - https://github.com/chapel-lang/chapel/issues/10415

Where I imagine we might support a more lightweight mechanism that uses a processor atomic to track how much memory is allocated.

For now, I'd recommend avoiding things like `memoryUsed` in production code and instead tracking memory estimates yourself

**Comment by mhmerrill** [comment]
@ronawho we are only checking `memoryUsed()` on allocation of a new symbol table entry and once at the beginning of some of the message processing functions like `ArgsortMsg()` which use large amounts of memory. In the mem-usage branch the server must be run with `--memTrack=true` to activate the feature.

**Comment by mhmerrill** [comment]
so I ran the arkouda benchmarks against the server with `--memTrack=true` and without. The performance results looked very close. There may be an impact of `--memTrack=true` but it does not show up in the benchmarks.

**Comment by ronawho** [comment]
Hmm, ok. For occasional, non-concurrent large allocations the cost might not be terrible, but we've seen over a 100x overhead for benchmarks that do concurrent allocation
