### ISSUE TITLE
Make getting the host name more elegant

### ISSUE THREAD

**Issue by bradcray** [mhmerrill/arkouda#164]
The following Arkouda code is an admittedly clunky way of getting the hostname of locale 0:

https://github.com/mhmerrill/arkouda/blob/a99a38e525f591615043c5e0db184d5a1943cfb2/src/ServerConfig.chpl#L41-L54

Some ways to improve this:

* read directly from the spawned command's stdout?
* call out to an extern C routine that returns the hostname?
* introduce a Chapel library routine that returns a node's hostname?

Note that I was originally thinking that `Locales[0].name` was the way to do this, but I don't think that would give a sufficiently fully qualified name for the client to be able to connect to the server as Arkouda is currently written.

**Comment by gbtitus** [comment]
Use `gethostname(3)` instead.  It's POSIX standard and works even on a Mac.

**Comment by gbtitus** [comment]
If the fully qualified name is required we'd probably need to call out to C code that would do a `getaddrinfo(3)` call starting with the value of `SLURM_NODENAME` and go from there as needed.

**Comment by bradcray** [comment]
> Use gethostname(3) instead. It's POSIX standard and works even on a Mac.

No fair giving a C solution without providing the Chapel code to wrap it!  :)

But...

> If the fully qualified name is required...

yeah, I think the fully qualified name probably is required in order for the client to find the server...

**Comment by gbtitus** [comment]
> ... the fully qualified name probably is required in order for the client to find the server ...

If the hostname in question is a compute node on an XC and you only need to be able to get to it from a system login node it seems to work in at least one case - I just tried it on an internal system with `srun hostname` and then `ping <whatThatSaid>`.  So that might be a start.

But if you need to get to it from anywhere else, including even an elogin for that same system, then yeah, it seems you need the qualified name.  My `ping` in that case said 'Name or service not known'.

**Comment by bradcray** [comment]
Oh, cool, I think that probably is sufficient.  Meanwhile, over on chat, I'm being told that Locales[0].name is almost certain to give the same thing as any other hostname-getting machinery, so maybe I should've stuck with my original instinct to begin with...

**Comment by gbtitus** [comment]
I said:

> But if you need to get to it from anywhere else, including even an elogin for that same system, then yeah, it seems you need the qualified name.

After thinking about it a bit more I suspect that at least for a Cray XC or similar system, one just might not be able to get directly to a compute from other than a system login node.  Certainly just adding an `.X.Y.Z` suffix to the name wouldn't suffice, since the compute node names are only unique within the system.  Across systems they're the same.  So for connections from other than a system login node one might need some kind of port-forwarding solution.
