### ISSUE TITLE
ak.arange(start, stop, stride) should accept all int types

### ISSUE THREAD

**Issue by gnat79** [mhmerrill/arkouda#292]
For example, sometimes I would like to create an array with code similar to this:

        x = ak.array([1,5,7,3,4,9])
        size = x.size
        ak.arange(x.max(), x.max() + size, 1)

which fails as x.max() is type ak.int64

I get a TypeError in the above example. Using server version 2020.02.04

**Comment by mhmerrill** [comment]
@reuster986 We have several places in the code which test for `isinstance(obj, int)` and `np.isscalar(obj)`. `np.isscalar(obj)` is not recognizing that `ak.int64` is a comparable type.

**Comment by hokiegeek2** [comment]
@mhmerrill @reuster986 @gnat79 This was fixed by [PR 686](https://github.com/mhmerrill/arkouda/pull/686/files) which checks for standard python as well as numpy scalars. I confirmed by executing the sequence @gnat79 posted in this issue:

![image](https://user-images.githubusercontent.com/10785153/110662412-7bac5800-8193-11eb-8ac4-3297d71f8f78.png)
