### ISSUE TITLE
Server should send error msg on unrecognized command

### ISSUE THREAD

**Issue by reuster986** [mhmerrill/arkouda#315]
When the main server loop encounters an unrecognized command, it just sends an empty message over the socket, which causes havoc in the client. It should instead send the string "Error: unrecognized command", so that the client can raise an exception.

**Comment by mhmerrill** [comment]
@bradcray Maybe someone on the chapel team could point us to a solution? Is there a way to use the `Reflection` module to do this???

**Comment by bradcray** [comment]
Can one of you point to where the empty message being sent back to the client is coming from, or is it unknown?  It seems as though this could be fixed by simple control flow, without relying on Reflection, but I could be mis-anticipating where this case is coming from.  For example, I'm imagining a big switch statement or conditional that handles messages, and the final `otherwise`/`else` case returning the error Bill's requesting.

**Comment by mhmerrill** [comment]
I put this in the wrong issue, it was meant for another issue, sorry.
> Can one of you point to where the empty message being sent back to the client is coming from, or is it unknown? It seems as though this could be fixed by simple control flow, without relying on Reflection, but I could be mis-anticipating where this case is coming from. For example, I'm imagining a big switch statement or conditional that handles messages, and the final `otherwise`/`else` case returning the error Bill's requesting.
