### ISSUE TITLE
Question: Can I build a Pandas dataframe in parallel?

### ISSUE THREAD

**Issue by buddha314** [mhmerrill/arkouda#404]
Please forgive this is it's way off topic.  In the construction of simulations, I often want do something like the below.  Basically for every epoch keep a record of the agent state.

```python
history = []

for agent in agents:
  agent_state = update_agent_state(agent)
  history.append(agent.state)
```

Now, because Chapel is bad-ass, I can run all these agent updates with a `forall` or something in parallel.  I have not experimented much with saving that epoch data to hdf5 or anything. But in python it would be nice to append a pandas dataframe (to the extent the memory can support it).  Is there a way to 

1. Run the agent updates in parallel
1. Update a global object like a Pandas dataframe

using Arkouda?  Thanks for your patience.

**Comment by mhmerrill** [comment]
@buddha314 we have several contenders for some data frame functionality but we have not been able to release code (from us).
We usually just keep a dictionary of Arkouda pdarrays a.k.a. a poor-man's dataframe. We cannot use Pandas directly because it wants to get into the internals of it's NumPy arrays in some cases. There is a PR #397  we are currently looking at with some dataframe functionality, You can see the discussion there.

**Comment by mhmerrill** [comment]
@buddha314 there are several samples of using Arkouda to do data-frame like things and also more complex examples in the repo. There are better examples which other people have constructed but here are links to a few in the repo...

- look at some of the toys like https://github.com/mhmerrill/arkouda/blob/master/toys/connected_components.py
- look at some of the files in https://github.com/mhmerrill/arkouda/tree/master/tests/deprecated
- one specific file is https://github.com/mhmerrill/arkouda/blob/master/tests/deprecated/mikes_lanl_io.ipynb
