### ISSUE TITLE
workflow for building and checking in arkouda/docs into the repo for github pages to host

### ISSUE THREAD

**Issue by mhmerrill** [mhmerrill/arkouda#428]
Remember we have `docs/` in the `.gitignore` file so we don't get rebuilt docs on every PR.

Strawman workflow for adding new arkouda doc build (`make doc`) to repo for github pages to host

1. create branch for new doc build from master
1. build docs in branch populating the `arkouda/docs` directory
1. add the generated doc files to the commit using the force flag on `git add -f docs/` to override the .gitignore entry of docs/
1. push branch to github arkouda repo
1. open PR for the branch
1. approval and merge of new docs into master branch

or not...

**Comment by mhmerrill** [comment]
Please review and comment on this if you have an opinion or insight: @reuster986 @hokiegeek2 @BryantLam @bradcray @ronawho 
Point others who might have an opinion or value to add to this issue.

**Comment by bradcray** [comment]
My main reaction is: how bad would it be if `docs/` was not listed within `.gitignore`?

I tend to be of two minds for generated files like this whose contents I care about:  On one hand, I like them to be in the repo in order to track their history and make sure they don't change in surprising ways.  In the Chapel repo, the files generated by `bison` and `flex` are like this in that they're in the repo, but only refreshed when the user explicitly asks for them (but we don't use `.gitignore` files on them; we just don't run the `make` command that refreshes them very often which is why I asked the question in the previous paragraph).

On the other hand, our `chpldoc`-generated docs are not under revision control, and are just auto-generated for the website whenever a new PR is merged.  This is nice in that it's convenient (no need to explicitly re-make the docs and commit them); but on the other hand, it's a little worrisome in that a commit could break some aspect of the docs (in the sense of their content or formatting, not whether or not they built correctly) without our ever noticing because we're never looking at and merging diffs of the doc files themselves.

**Comment by mhmerrill** [comment]
Maybe I should create and arkouda_doc repo to hold the built docs...

**Comment by BryantLam** [comment]
I have a hard-line opinion that I never commit byproducts into the history if it can be generated. This guideline cuts down on polluting the history and making clones take longer.

For hosting the documentation, my thoughts would be to create a separate GitHub-Pages-specific repo for the docs and set up a CI runner to build the docs and push to it periodically. There would be some complexity in making sure the runner can correctly commit+push (i.e., making sure the runner correctly does nothing if the docs haven't changed) and setting up the protected repo so that *only* that runner can push to it.

The `gh-pages` orphaned branch would also work, but because it is homed in this main project, any user that `git clone`s would get all branches including it. Maybe that's a good thing if users want to have immediate offline access to the documentation, but this is&mdash;in a way&mdash;another form of history pollution.

**Comment by bradcray** [comment]
> my thoughts would be to create a separate GitHub-Pages-specific repo for the docs and set up a CI runner to build the docs and push to it periodically.

Is a human in the loop for reviewing these pushes?  If not, what's the benefit of storing them in a repo?  If so, what's the periodicity of the updates?

**Comment by hokiegeek2** [comment]
@BryantLam definitely good points! One key about the approach that @mhmerrill details above is that it leverages the [Github Pages](https://pages.github.com/) framework to host Arkouda docs for free in a manner that integrates into the Arkouda github repo. Another is that it ensures we maintain a git history of all documentation as well. 

@bradcray yes, each docs PR would be reviewed prior to merging into the master, so definitely 1..n humans in the loop. The benefits for storing in the repo would be (1) leveraging Github Pages to host Arkouda docs and (2) keeping docs under version control. From my perspective, docs updates would occur if any new documentation content from the Chapel or Python doc generation or if rst files are updated/added.

As @mhmerrill mentioned, it seems like it would be possible to host the docs in a separate repo. The approach Mike outlined above is the most straightforward way to get the docs hosted and available.

There is a nifty concept in git called sparse checkout, a good discussion of which is available [here](http://jasonkarns.com/blog/2011/11/15/subdirectory-checkouts-with-git-sparse-checkout/). This would be a way of avoiding pulling down the docs folder.

**Comment by mhmerrill** [comment]
John and I were talking about https://readthedocs.org/ and it claims to integrate with GitHub in a automated way of building the docs when certain events happen. I requires a `.readthedocs.yml` file in the repo to direct the building of the docs https://docs.readthedocs.io/en/stable/config-file/v2.html

**Comment by mhmerrill** [comment]
readthedocs can now mostly build and host the arkouda documentation
https://arkouda.readthedocs.io/en/latest/
we are currently building from this arkouda branch 
https://github.com/mhmerrill/arkouda/tree/mhmerrill-doc-req
We are not currently able to build the chpldoc based documentation.

**Comment by hokiegeek2** [comment]
@mhmerrill NICE!!!!

**Comment by bradcray** [comment]
Ah, the piece I was missing was that GitHub pages requires the docs to be in a repo, thanks!

**Comment by hokiegeek2** [comment]
@mhmerrill what's the error in the chpldoc generation?

**Comment by mhmerrill** [comment]
> @mhmerrill what's the error in the chpldoc generation?

@hokiegeek2 I don't know how to run `chpldoc` in the processing. I imagine you can add it to the YAML file somehow but couldn't find the necessary information to do so.

**Comment by hokiegeek2** [comment]
@mhmerrill content.rst fix worked! So the Python autodoc is running, but the link is not showing up in content.rst. Hopefully that's a config thing.

**Comment by mhmerrill** [comment]
I am going to close this since we went with readthedocs.
