### ISSUE TITLE
Improve performance of string gather

### ISSUE THREAD

**Issue by reuster986** [mhmerrill/arkouda#527]
@ronawho @mhmerrill This is more of a brainstorming question, rather than a hard requirement. These days, more and more users find themselves waiting on gathers of string arrays (either explicitly or inside GroupBy), and I am wondering if there is a way to speed this up. String gather has two steps: gathering the string offsets (which is just an int64 gather, so it's fast), and gathering the string bytes, which is the slow part. The code for sending the string bytes from src to dst is here:

https://github.com/mhmerrill/arkouda/blob/652e89fbdedb17ca6cba4e3b760055797bc96143/src/SegmentedArray.chpl#L220-L260

On UGNI or single-locale, it is just an unorderedCopy. On non-UGNI, multi-locale systems, the code uses aggregation, but in order to do so it has to pre-compute a dest-local version of the byte indices, which is slow and memory-intensive. 

With the recent updates to aggregation, is there a better way to use aggregation across the board without first localizing the indices to one side, or is that still necessary?

Are there any other ways to speed this up? Would it be faster to use an aggregator inside an `on` clause to ensure locality?

**Comment by ronawho** [comment]
None of the recent aggregation changes have improved the situation WRT to localization. Currently either the src or dst always has to be local.

That said, I'm sure there's something we can do to optimize this. 

Do you have a performance test I can use to start looking at this? Either an arkouda or standalone chapel benchmark would be fine.

**Comment by ronawho** [comment]
I rebased a prototype branch for a general purpose CopyAggregator. It's optimized for when either src or dst is remote. It will work if both src and dst are remote, but it falls back to blocking GETs of the src, so if that's a common case it won't be very fast -- https://github.com/mhmerrill/arkouda/compare/master...ronawho:copyagg

The other thing that comes to mind is we could so something similar to what we did for `computeSipHashLocalized()` in https://github.com/mhmerrill/arkouda/pull/287. Assume most operations will be local, but if they aren't do a single bulk GET to localize. There are disadvantages to this as well if your string sizes are highly non-uniform, but it seemed to work ok in practice at least for siphash. More discussion on that is near the end of https://github.com/mhmerrill/arkouda/issues/266

**Comment by reuster986** [comment]
@ronawho I  modified `benchmarks/gather.py` to run with `--dtype=str`. The code is on the `string-gather-benchmark` [branch](https://github.com/mhmerrill/arkouda/blob/string-gather-benchmark/benchmarks/gather.py).

When I run `gather.py -n 10_000_000 -d str` on 30 nodes of Cray XC, I get 0.47 GiB/sec, vs. 61.3 GiB/sec for `-d int64`.

I like your idea of doing something similar to SipHash. I believe most operations will be local, and the non-uniformity should not be too bad, so this approach sounds promising. If we want to explore the effect of non-uniformity, we can modify the benchmark to use `ak.random_strings_lognormal(2, 2, Nv)` or something similar.

**Comment by ronawho** [comment]
Thanks. I don't think we can match int64 performance, but we should be able to close that gap. Since strings are using `uint(8)`, the performance might end up being more comparable to gather with `-d bool`  (It takes about the same time to aggregate 10M ints as it does bools so the the raw time of bool/int64 gather is similar, but the rate for int64 is higher since each operation is larger in size.)  And even then there will likely be non-trivial overhead for gathering strings compared to bools given the complexities of the segmented array and strings potentially being spread across 2 locales.

But still, that .5 GiB/s sure seems low -- will start looking

**Comment by ronawho** [comment]
And just to establish a baseline here's what I see on 16 nodes of an XC with 24-core ivybridge blades:

```
$ ./benchmarks/run_benchmarks.py gather -nl 16 --size 10_000_000 --dtype bool
Average time = 0.1162 sec
Average rate = 3.85 GiB/sec

$ ./benchmarks/run_benchmarks.py gather -nl 16 --size 10_000_000 --dtype int64
Average time = 0.1397 sec
Average rate = 25.60 GiB/sec

$ ./benchmarks/run_benchmarks.py gather -nl 16 --size 10_000_000 --dtype str
Average time = 28.8677 sec
Average rate = 0.26 GiB/sec
```

**Comment by ronawho** [comment]
@reuster986 it looks like your "non-ugni" code that uses aggregation provides a significant speedup on ugni too. Below is a comparison of your manually aggregated version ("aggregation at the expense of memory") vs. unordredCopy, vs. the prototype CopyAggregator using https://github.com/mhmerrill/arkouda/compare/master...ronawho:string-gather-experiments:

```
$ ARKOUDA_SERVER_STRING_GATHER_MODE=manualSrcDstAgg ./benchmarks/run_benchmarks.py gather -nl 16 --size 10_000_000 --dtype str --trials=1
Average time = 1.0549 sec
Average rate = 7.06 GiB/sec

$ ARKOUDA_SERVER_STRING_GATHER_MODE=unorderedCopy   ./benchmarks/run_benchmarks.py gather -nl 16 --size 10_000_000 --dtype str --trials=1
Average time = 30.8489 sec
Average rate = 0.24 GiB/sec

$ ARKOUDA_SERVER_STRING_GATHER_MODE=copyAgg         ./benchmarks/run_benchmarks.py gather -nl 16 --size 10_000_000 --dtype str --trials=1
Average time = 7.7694 sec
Average rate = 0.96 GiB/sec
```

So I see:
 - ~0.25 GiB/s for the current unorderedCopy implementation
 - ~0.95 GiB/s for the prototype CopyAggregator implementation
 - ~7.05 GiB/s for your existing "non-ugni" aggregated implementation

To start it seems like you could just use the existing "non-ugni" aggregated implementation under ugni too. I seems to have dramatically better performance, and at a glance the memory overhead doesn't seem too unreasonable to me. 

---

Misc details, feel free to ignore:

<details>

By the way, unorderedCopy for 1-byte things is not very optimized under ugni. The Aries NIC requires that GETs are 4-byte aligned in order to do direct RDMA. 1-byte things can't be 4-byte aligned so we have to use bounce-buffers and ordered/blocking GETs instead. For int64 we use 0-copy RDMA with unordered/non-blocking GETs. https://github.com/mhmerrill/arkouda/issues/318 and https://github.com/mhmerrill/arkouda/pull/507 have some more notes.

</details>

**Comment by ronawho** [comment]
Ah, and looking back at https://github.com/mhmerrill/arkouda/pull/275 it turns out that you already added a pure Chapel StringGatherSpeedTest. For that benchmark and string-gather-experiments branch here's what I see:

```
$ make test-bin/StringGatherSpeedTest

$ ARKOUDA_SERVER_STRING_GATHER_MODE=manualSrcDstAgg ./test-bin/StringGatherSpeedTest --N=1_000_000 --MEANLEN=100 -nl 16
Permuted 1000000 strings (94.0 MB) in 0.16 seconds (585.04 MB/s)

$ ARKOUDA_SERVER_STRING_GATHER_MODE=unorderedCopy   ./test-bin/StringGatherSpeedTest --N=1_000_000 --MEANLEN=100 -nl 16
Permuted 1000000 strings (96.0 MB) in 4.84 seconds (19.85 MB/s)

$ ARKOUDA_SERVER_STRING_GATHER_MODE=copyAgg         ./test-bin/StringGatherSpeedTest --N=1_000_000 --MEANLEN=100 -nl 16
Permuted 1000000 strings (95.0 MB) in 1.43 seconds (66.51 MB/s)
```

Same trend as the gather.py benchmark, just faster to build. If I revert https://github.com/mhmerrill/arkouda/pull/507 the `manualSrcDstAgg` is much slower (35 MB/s) so I think that explains why it's faster now, but not when you originally special cased in https://github.com/mhmerrill/arkouda/pull/275

**Comment by ronawho** [comment]
My current recommendation is to partially revert https://github.com/mhmerrill/arkouda/pull/275 and use the existing aggregation implementation for ugni. I think that will get you a substantial speedup.

I was thinking it might be worthwhile to just use the aggregated case for `comm=none` to reduce the number of implementations and improve testing coverage, but that does have a significant performance hit. On a 24-core haswell system (nightly chapcs testing) I see performance go from ~2150 MB/s to ~350 MB/s. I don't know how important comm=none performance is for that gather, so I'll let you make that call:

```
$ make test-bin/StringGatherSpeedTest

$ ARKOUDA_SERVER_STRING_GATHER_MODE=unorderedCopy   ./test-bin/StringGatherSpeedTest --N=10_000_000 --MEANLEN=100
Permuted 10000000 strings (964.0 MB) in 0.45 seconds (2139.45 MB/s)

$ ARKOUDA_SERVER_STRING_GATHER_MODE=manualSrcDstAgg ./test-bin/StringGatherSpeedTest --N=10_000_000 --MEANLEN=100
Permuted 10000000 strings (959.0 MB) in 2.81 seconds (341.62 MB/s)
```

**Comment by ronawho** [comment]
https://github.com/mhmerrill/arkouda/pull/532 reverted just the ugni part, leaving the `comm=none` optimization in. 

For additional optimizations -- I wonder if we could have an aggregator that aggregates the entire string section instead of a byte at a time. i.e. if there's a 64-byte string aggregate that with 1 call instead of 64 calls. That would require some additional aggregation storage to track the length of things and would require care when a string crosses a locale boundary, but it would pretty dramatically reduce the number of calls to the aggregator.

And we may also want to increase the aggregator buffer size. Today we just use 4096 element buffers. That results in a 32K message for `int(64)`, but only a 4K for `uint(8)` so it's likely not using network bandwidth as efficiently.

**Comment by reuster986** [comment]
Excellent observations! And thanks for the PR; I think that is the right call.

I was thinking something similar to your suggestion about multi-byte string aggregation, but I don't know how to write it. Does the current srcAggregator support slice-like (multi-byte) arguments, or are you talking about adding new functionality?

Good point about buffer size -- I will have to do some tuning on our system.

**Comment by mhmerrill** [comment]
Maybe buffer size should be divided by data type size or something... but doesn't the buffer also contain addresses?

**Comment by ronawho** [comment]
> I was thinking something similar to your suggestion about multi-byte string aggregation, but I don't know how to write it. Does the current srcAggregator support slice-like (multi-byte) arguments, or are you talking about adding new functionality?

No, currently it doesn't support that, today it only supports aggregating a single element. Supporting multi-element aggregation would be new functionality.

> Good point about buffer size -- I will have to do some tuning on our system.

> Maybe buffer size should be divided by data type size or something... but doesn't the buffer also contain addresses?

Right, the buffer contains addresses too. I was thinking we could specify the number of bytes for the complete buffer and then have the aggregators figure out how to split that between addresses and data.

I suspect that longer term we'll also really want some sort of auto-tuning for buffer size. Either something the server does automatically at startup, or if the tuning takes long enough, maybe something we have the user do while building.

**Comment by reuster986** [comment]
I think string ops are in pretty good shape now, so I'll go ahead and close this.
