### ISSUE TITLE
What to do about `class == class` overloads in Arkouda?

### ISSUE THREAD

**Issue by bradcray** [mhmerrill/arkouda#603]
In https://github.com/chapel-lang/chapel/issues/13048, @BryantLam argued that `==` and `!=` should not be supported between classes, and generally speaking @mppf and I agreed with that notion, though it's taken us until this week to get around to implementing it (in https://github.com/chapel-lang/chapel/pull/16832).

The rationale for doing this relates to the fact that a class variable essentially stores a pointer to a class object.  Chapel already makes `=` overloads on classes illegal in order to avoid breaking the ability to store new pointer values into a class variable.  Symmetrically, the argument for disallowing `==` and `!=` overloads on classes is because their presence essentially breaks the ability to ask fundamental questions like "is this class variable storing `nil`?" or "are these two class variables pointing at the same object?"

In running testing for the PR mentioned above, I realized that Arkouda defines `==` and `!=` overloads between `SegString`/`SegString` pairs as well as between `SegString`/`string` pairs.  This issue asks what we should do about these cases.

* One option would be to replace the overloads and their uses in Arkouda with named functions like `equals()` and `notEquals()` or the like
* Another would be to push back on the consensus reached in https://github.com/chapel-lang/chapel/issues/13048 and suggest other changes/practices in the language for comparing class object identities.
* Another would be to wrap these Arkouda types in records, since records do support `==` and `!=` overloads
* We've also discussed in https://github.com/chapel-lang/chapel/issues/16830 whether class/class versions of these operators should be illegal but class/non-class versions legal, which would permit the `SegString`/`string` cases to continue working while still requiring the others to adapt.

I'd be curious for thoughts here from @mhmerrill, @reuster986, and @hokiegeek2.

**Comment by reuster986** [comment]
@bradcray thanks for raising this question here. I guess I would push back on the consensus and offer a dissenting opinion that `==` and `!=` should be supported for classes, because as a programmer I often want to evaluate whether two things are equivalent (not caring whether they point to the same address) and to define what "equivalence" means, and overloading `==` is a really intuitive and readable way to do that. In the same vein, I think new users would be thrown off by the inability to overload `==` and `!=` when all other operators are overloadable in Chapel and other languages that they're familiar with presumably support overloading `==` and `!=` (Python allows this, at least, and I'm pretty sure Julia does).

I appreciate the concern about wanting to be able to ask about `nil` and pointer equivalence, but since (I think) these cases are more rare than wanting to test for value equivalence, I would prefer to reserve `==` and `!=` for the latter and have named functions for the former -- maybe something like `.isNil()` and `.addressEquals(other)`? As a programmer, this seems to satisfy the principle of making it easy to express common/important ideas, but I'm not really a computer scientist, so maybe I'm blind to some other principle that would argue against this approach. 

Just my two cents.

**Comment by bradcray** [comment]
Hi Bill — I'd be nice to get some input from @BryantLam here as well if possible, since he was among those originally proposing to disable `==` and `!=` for classes.

After posting this yesterday, I did more "what do other languages do?"-style research and learned about `===` and `!==` in Swift (and then in Python) which could be another path forward here.  That led me to file this issue as a possibility:  https://github.com/chapel-lang/chapel/issues/16853

**Comment by bradcray** [comment]
[edit: wait wait wait, did I mis-read something last night?  I thought Python supported `===` but now I'm not finding it, so maybe I misunderstood something (it was late in the day).  I'll update/correct the previous note when I get my head on straight]

**Comment by bradcray** [comment]
My read on the situation is that there's general agreement among users that we should continue to support `==` and `!=` on classes and have some other means of doing class identity comparison to fall back on when users do overload these operators.  Closing this as resolved on this basis.
