### ISSUE TITLE
Array assignment in Chapel

### ISSUE THREAD

**Issue by zhihuidu** [mhmerrill/arkouda#641]
let A and B be two integer arrays and B=A, then let
var Perm= radixSortLSD_ranks(A);
B=A[Perm];
A=A[Perm];
At this point, I find B!=A, which means that the array assignment in Chapel is not parallel. In other word, Chapel will not first keep all A[Perm] elements in a temperal array and then assign the temperal array to A in parallel.
for example, A=B=
7 5 2 1 7 7 4 8 3 7 7 4 6 5 4 5
we will get Perm=
3 2 8 6 11 14 1 13 15 12 0 4 5 9 10 7
Then we can get B and A[Perm] that have  the same values
1 2 3 4 4 4 5 5 5 6 7 7 7 7 7 8
However, after A=A[Perm], A will be
4 3 3 4 7 4 5 7 7 7 7 7 7 7 7 7
which will not have the same value as B.
I think Chapel should let B and A have the same value if Chapel supports parallel array assignment.
Or there is something wrong in my test? 
@bradcray

**Comment by bradcray** [comment]
Hi @zhihuidu — This is working as expected, but an understandable point of confusion for someone new to Chapel.  Chapel does support parallel array assignment, but the semantics differ from traditional array languages.  Specifically, given Chapel arrays `A` and `B`, and an expression like:

```chapel
A = B;
```

Chapel defines the semantics of this as:

```chapel
forall (a,b) in zip(A,B) do
  a = b;
```

An implication of this is that when the RHS and LHS refer to overlapping sections of the same array, a race condition exists.  Specifically, your first example `B = A[Perm];` is safe and translates to:

```chapel
forall (b, i) in zip(B, Perm) do
  b = A[i];
```

But your second case, `A=A[Perm];`, translates to:

```chapel
forall (a, i) in zip(A, Perm) do
  a = A[i];
```

So values written to `A` in this loop by one task are likely to be read by other tasks running other iterations in parallel.  The obvious way to work around this is to split the assignment into two statements:

```chapel
{
  var T = A[Perm];
  A = T;
}
```

If you're interested, one of the main reasons for this approach in Chapel was to avoid the requirement of array temporaries to implement the language.  For example, whole-array statements like `A = B + C * D;` get translated to:

```chapel
forall (a, b, c, d) in zip(A, B, C, D) do
  a = b + c * d;
```

rather than:

```chapel
var T = C * D;
var T2 = B + T;
var A = T2;
```

as in a typical array language that semantically implements an operator at a time.  This results in reduced overall storage, which can be important for programs with huge arrays like Arkouda.  And it typically results in better cache utilization, particularly when a single array appears in the RHS expression multiple times.

Of course, the main downside is that it can be a surprise for people accustomed to traditional array language semantics.  Fortunately, in our experience, it's been fairly rare for people to step into this pit, but as your example shows, it does happen.  (We have considered what it would take to create a compiler warning to alert new users to potential race-y cases like this, but have not yet implemented it).

**Comment by zhihuidu** [comment]
@bradcray thanks for your quick reply!
Yes, you are right. I do not know Chapel array assign/forall have different semantics with F90 /HPF, I am learning Chapel and just assume that they have the same semantics. 
The semantics of F90/HPF will  really need more temporal memory to keep its sementics.

**Comment by bradcray** [comment]
@zhihuidu — Can this issue be closed, or do you feel something more needs to happen in order to do that?  Thanks.

**Comment by zhihuidu** [comment]
Yes, I have understood the problem and you can close it. Thanks!
@bradcray
