### ISSUE TITLE
string_test.test_ends_with periodically fails

### ISSUE THREAD

**Issue by hokiegeek2** [mhmerrill/arkouda#646]
![image](https://user-images.githubusercontent.com/10785153/106052816-0ccde080-60b8-11eb-882f-17546bfa59ff.png)

**Comment by reuster986** [comment]
This is the same failure mode we've seen before; namely, where the last string in the array ends with the delimiter itself. My suspicion is that arkouda is not finding `delim` in the last string. This should be pretty easy to confirm in an interactive session (unfortunately, I'm not teleworking anymore). If true, then it's probably due to an off-by-one error in the Chapel code.

**Comment by hokiegeek2** [comment]
@reuster986 Gotcha, yeah. What's kinda odd to me is that I've really not seen this error in a really long time, and I've now seen it twice over the course of the last week. I will definitely test it out as you described above.

**Comment by hokiegeek2** [comment]
Happened again:

![image](https://user-images.githubusercontent.com/10785153/107276624-4f30df00-6a21-11eb-8fe6-7ffcec81ed42.png)

**Comment by hokiegeek2** [comment]
Fixed two more errors in string_test.test_ends_with due to wrong pdarray being passed into run method.
