### ISSUE TITLE
Check benchmark rate calculation

### ISSUE THREAD

**Issue by ronawho** [mhmerrill/arkouda#674]
For argsort we try to report the sort rate (results per second) and not how much data is being transferred under the covers. See https://github.com/mhmerrill/arkouda/issues/531 for discussion on that.

In some other benchmarks I'm wondering if we're mistakenly reporting the amount being transferred instead.

- Numeric gather/scatter:
  - We report `3 * iv.size * iv.itemsize`. Why * 3?
- String gather:
  - Rate includes offsets too, which I think is wrong?
- String groupby:
  - Rate also includes offsets
- At a glance the other benchmarks look right to me

**Comment by ronawho** [comment]
@mhmerrill @reuster986 I feel somewhat confident we should remove offsets from the string gather/groupby calculations. I'm less sure about why gather/scatter has the ` * 3` multiplier. I would not be surprised if that's right, but I couldn't explain why myself.

**Comment by mhmerrill** [comment]
@ronawho I think the gather metric is ok because we just use a constant. The thought behind the sort is we wanted to be algorithm agnostic, so different algorithms could be used and we could still compare them base on something like keys per sec.

**Comment by reuster986** [comment]
I concur with @mhmerrill . I vaguely remember talking with him about a  year ago about two classes of benchmarks: a lower level designed to illuminate hardware performance and a higher level designed to measure algorithm performance from a user perspective. I think at the time we put (gather, scatter, scan, reduce, stream) in the lower level and argsort in the higher level. So I think that's why the lower level benchmarks measure rates in amount of actual data transferred while argsort measures rate in terms of elements visible to the user. Most benchmarks we've added since then are upper-level (coargsort, groupby, aggregate).

So based on that principle, I would say we should keep the `3 *` in gather/scatter and include offsets in string gather, but we should ignore offsets in string groupby. I realize I was the one who included offsets in string groupby -- I wasn't really thinking about this distinction when I wrote it, but this discussion is helping me clarify my thoughts.

**Comment by ronawho** [comment]
> So based on that principle, I would say we should keep the 3 * in gather/scatter and include offsets in string gather, but we should ignore offsets in string groupby. I realize I was the one who included offsets in string groupby -- I wasn't really thinking about this distinction when I wrote it, but this discussion is helping me clarify my thoughts.

Gotcha, that sounds good to me. What originally caused me to open this issue was comparing int and str gather performance. I've been just comparing the rates but that doesn't quite reflect the amount of time a user has to wait so I was wondering if it made sense to not include offsets to make int/str comparisons more apples-to-apples. I'm on board with the low-level hardware measurement argument though, so leaving gather as-is sounds good to me.

**Comment by mhmerrill** [comment]
I think this can be closed based on our discussion. Reopen if you want @ronawho

**Comment by ronawho** [comment]
I think based on this discussion the one action item was to change groupby to stop including the offsets in the rate calculation.
