### ISSUE TITLE
testConcatenate  fails at 6+ locales

### ISSUE THREAD

**Issue by ronawho** [mhmerrill/arkouda#706]
Added in https://github.com/mhmerrill/arkouda/pull/701, `testConcatenate` is failing in our nightly multi-locale testing. Nightly testing uses 16 locales, but I can reproduce the failure with 6 locales.

The error is a segfault on the server, so I don't have a useful backtrace yet.

**Comment by ronawho** [comment]
@hokiegeek2 using a build with `ARKOUDA_DEVELOPER=true` to get runtime checks I see:

```
src/ConcatenateMsg.chpl:126: error: halt reached - array index out of bounds
note: index was 5 but array bounds are 0..4
src/ConcatenateMsg.chpl:121: error: halt reached - array index out of bounds
note: index was 5 but array bounds are 0..4
```

**Comment by hokiegeek2** [comment]
@ronawho operator_tests or categorical_test?

![image](https://user-images.githubusercontent.com/10785153/111349744-c9bfd080-8657-11eb-95a9-1cf2f9073f0e.png)

**Comment by ronawho** [comment]
`categorical_test.py`

**Comment by hokiegeek2** [comment]
The code where this error occurs is here:

![image](https://user-images.githubusercontent.com/10785153/111461439-9894de00-86f3-11eb-9f5f-7285e75590e1.png)

**Comment by reuster986** [comment]
I think I see what's going on. When the size of an input array is less than `numLocales - 1`, then multiple locales will have zero-length `localSubdomain`s at the end of the array. Since the if/else only special-cases the last locale, the second-to-last locale (and possibly others) will try to evaluate `e.a[e.aD.localSubdomain().high + 1]`, but because it and its followers are empty, `localSubdomain().high` is the end of the array, and `.high + 1` is out of bounds. This could (probably) be fixed with a temporary variable before line 126, e.g.

```chpl
} else {
  const lastSegIdx = min(valSize, e.aD.localSubdomain().high + 1);
  mybytes = e.a[lastSegIdx] - firstSeg;
}
```

**Comment by hokiegeek2** [comment]
@reuster986 Yup, I figured that out when I tested 6 and 7 locales earlier. I upped array size and tests pass. PR coming soon!

**Comment by hokiegeek2** [comment]
@reuster986 and yeah, I'll add a guard condition in ConcatenateMsg

**Comment by hokiegeek2** [comment]
merged [PR](https://github.com/mhmerrill/arkouda/pull/708), issue resolved

**Comment by reuster986** [comment]
I don't want to close this until the guard condition is added to `concatenateMsg`

**Comment by reuster986** [comment]
@hokiegeek2 I'm ok with closing this now, since you started a separate issue for the underlying error.
