### ISSUE TITLE
Registration should update `pdarray.name` in place

### ISSUE THREAD

**Issue by reuster986** [mhmerrill/arkouda#729]
Currently, to safely use a registered array, a user must reassign the array:

```python
a = a.register('myarray')
```

In my experience, users typically expect registration to be an in-place operation:

```python
a.register('myarray')
```

but after this operation, `a.name` is still `id_123`, not `myarray`. This tends to cause confusion, e.g. after calling `ak.clear()`. 

Having the registration function update `a.name` in-place would provide more intuitive usage and would also make it easier to register complex objects without having to reassign every attribute.

**Comment by mhmerrill** [comment]
@reuster986 this is ok with me. I am not sure if you recall but we discussed this when I did the implementation.

**Comment by reuster986** [comment]
@mhmerrill Ah, I forgot about that -- I apologize if I started us down the wrong path. I think after seeing it used in a few real applications, it's easier to see what's important. I'm trying to recall why we settled on an out-of-place approach, but I can't remember...

Just to clarify what I'm thinking, something like:

```python
# For base pdarray
class pdarray:
    ...
    def register(self, name):
        # Send the server message and check for success
        ...
        self.name = name
        # Keep backwards compatibility for code that does `a = a.register(name)`
        return self

# And for complex objects:
class GroupBy:
    ...
    def register(self, name):
        # Register each attribute array with its own suffix
        for attrib in ('segments', 'permutation', 'unique_keys'):
            array = getattr(self, attrib)
            array.register('_'.join([name, attrib]))
        # Backwards compatibility
        return self
```

In this paradigm, each client-side class would have its own `.register` method. Does that seem like a viable approach?

**Comment by mhmerrill** [comment]
@reuster986 i think this is ok, we will need to make some changes in the server also.

**Comment by mhmerrill** [comment]
@reuster986 I took a look at what needs to change to support this change in the server, client code will have to change also.

server side changes:
- change to `RegistrationMsg.chpl`, change the returned `"created ..."` message in `registerMsg()` to just return `"success"`, we will no longer need to call `st.attrib()` since we will not be creating a new object on the client side
- change to `MultiTypeSymbolTable.chpl`, the functionality of `regName()` will have to change to add the new name to the symbol table, point new name at the symbol table entry, and delete the old name from the `tab`
- there may be more changes but I don't see them at this time.

**Comment by mhmerrill** [comment]
@reuster986
On the client side:

- change to `pdarrayclass.py`, change `register_pdarray()` to set the `name` field instead of creating a new `pda` object, this precludes us from taking a string name as an argument (I think), return value should be changed to `None`
- change to `pdarrayclass.py`, `pdarray.register()` to call `register_pdarray()` and no longer return ir, return should be changed to `None`
- changes to `strings.py`, changes to `register()` and `register_helper()`, new `Strings` object is no longer returned, return value changed to `'None', and code  gets much simpler (I think)
- there are currently no registration function for GroupBy objects but with this change it will be simple to implement (I think)
- There might be more changes but I currently don't see them.

**Comment by mhmerrill** [comment]
@reuster986 I have assigned @pierce314159 and @glitch to get their feet wet.

tasks are:
- [ ] change server code
- [ ] change client code
- [ ] update documentation
- [ ] update tests

**Comment by reuster986** [comment]
@mhmerrill I agree with everything, except I think the registration functions should return `self` instead of `None`, to preserve backwards compatibility with the current usage.

**Comment by mhmerrill** [comment]
> @mhmerrill I agree with everything, except I think the registration functions should return `self` instead of `None`, to preserve backwards compatibility with the current usage.

sounds good to me.

**Comment by glitch** [comment]
Sounds good.

In the future if we start supporting composition we can consider having a _display_name_ and an internal_id where all object refs in the SymTab/GenSymEntry use the internal_id and on the client side splice in the _display_name_ for user interaction.

**Comment by glitch** [comment]
Just to note a change in functionality, previously you could register the _same_ item multiple times ( as can be seen in this [test](https://github.com/mhmerrill/arkouda/blob/b5ca95d659471392c81db1439d5ea9ae17e8c267/tests/registration_test.py#L98) ).  A  _shallow copy_ on the client side (2 client pdarrays pointing to the same object on the server) was produced when the message returned from the server with the object meta-info was passed to the pdarrayclass.__init__ constructor.

This changes with in-place modification.  Since a shallow copy no longer happens on the client side, we can only have one registration reference to the object.  If you register the same object twice in succession the old name in the registry will be replaced with the new one.

**Comment by glitch** [comment]
@pierce314159 and I noticed that a function to list the contents of the registry doesn't exist so issue #734 was created.

Additionally, it seems like a boolean function `pdarrayObj.isRegistered` would be nice to have from both an interactive user perspective and testing perspective.  I'm going to create another issue for it but will likely submit it in the same PR as this one.

**Comment by glitch** [comment]
@mhmerrill I have a quick question but first a quick background of where I'm at:

- pdarrayclass has two sets of register/unregister functions
    - instance methods, `register(name)`/`unregister()`
    - static methods,  `register_pdarrayclass(pda, name)`, `unregister_pdarray(pda)
- strings only has instance methods `register(name)`/`unregister()`
- GroupBy ... TBD

My understanding of Why?
Originally `register_pdarrayclass` took Union[str, pdarrayclass] for the first arg, but the in-place update reduces this to only taking the object.  As for the strings case, since the strings object didn't have a name attribute, it only had an instance method to register/unregister.

I'd like to make this consistent across the 3 classes.

- Both static and instance methods (one would be a convenience method that passes through to the other)
- Only static methods, i.e.  register_pdarrayclass(pda_obj, "with_this_name")
- Only instance methods, i.e.   ojb.register("use_this_name") 

Which way do you want to go?

**Comment by hokiegeek2** [comment]
@glitch @mhmerrill I wonder if it makes more sense just to have a registration module and centralize all the logic there including register/unregister, list_registered_objects, etc...

**Comment by glitch** [comment]
> 
> 
> @glitch @mhmerrill I wonder if it makes more sense just to have a registration module and centralize all the logic there including register/unregister, list_registered_objects, etc... Otherwise, seems like were duplicating code unless I am missing something.

You know, I was thinking about this too, but there is some specialized logic for each type of object, i.e. strings needs to register two internal pieces, groupby has 4, pdarrayclass has 1.

That aside, one possible design would be to have something like `register_obj(a, "with_name")` and then we can inspect the object type and route it to its internal method  `obj._register('with_name')` etc.

**Comment by reuster986** [comment]
My personal preference as a user would be for instance methods across the board, unless there is some behavior that cannot be expressed that way, or some other compelling design reason.

**Comment by glitch** [comment]
> 
> 
> My personal preference as a user would be for instance methods across the board, unless there is some behavior that cannot be expressed that way, or some other compelling design reason.

Thanks @reuster986 that's good feedback.  I believe everything can be done with instance methods since it's moving to an in-place operation.

**Comment by hokiegeek2** [comment]
@glitch @reuster986 ah, makes sense since there is custom logic for Strings (and Categoricals if we register those at some point). So yeah, makes sense to make register/unregister as in instance attribute as Bill indicated.

**Comment by glitch** [comment]
I can almost talk myself into the need for a static unregister_object("name") in the event that a user loses track of their python objects.  Presumably, they'd be able to fetch registration info for everything from the server and then want to be able to start dropping stuff manually.

However, that would violate an object's encapsulation and expose a lot of the internals that folks shouldn't be directly touching lest something break.  i.e. dropping the offsets portion of a `strings` object.  We could add a bunch of guards to protect against it, but that seems self-defeating.

**Comment by hokiegeek2** [comment]
@glitch solid points! I think the concept of a static unregister_object in my mind kinda leans into an idea I've been pondering for awhile: adding a User-Session construct to Arkouda, an attribute of which could be a dict containing references to the user's registered objects.

**Comment by glitch** [comment]
> 
> 
> @glitch solid points! I think the concept of a static unregister_object in my mind kinda leans into an idea I've been pondering for awhile: adding a User-Session construct to Arkouda, an attribute of which could be a dict containing references to the user's registered objects.

Yeah kind of like a user workspace right?  I was just thinking along the same lines.

**Comment by hokiegeek2** [comment]
@glitch yup, and I like your terminology of "user workspace" better.

**Comment by mhmerrill** [comment]
@glitch @pierce314159 @hokiegeek2 @reuster986 I didn't intend for you to reinvent the world with this task, new ideas are fine but I don't want too many changes all at once. I thought I made things clear enough and I want something that gives basic functionality first and then we can enhance with subsequent PRs.

**Comment by glitch** [comment]
@mhmerrill and I chatted and decided that GroupBy is complex enough to warrant it's own ticket, so I'm going to leave that out for now.  The changes going forward are basically going to be:

- Change pdarrayclass to in-place registration (and drop the static register method)
- Change strings to in-place registration

**Comment by glitch** [comment]
Yikes, there was an unintended consequence here (which I'd classify as a bug, thanks for finding it @pierce314159 !) where registering two different objects with the same name overwrites the first object.  i.e.
```
a = ak.ones(3, dtype=ak.int64)
b = ak.ones(3, dtype=ak.int64)
b.fill(2)
a.register("foo") 
b.register("foo")
str(a) # outputs  [2, 2, 2] which is not necessarily what the user expected
```

The _correct_ behavior is to throw an error message back to the user letting them know that "foo" has already been used to register an object.  The user can then either unregister the previous object to free up the name "foo" or register it with another name etc.

@mhmerrill  I'll roll up a fix & test case ASAP

**Comment by glitch** [comment]
Just to recap where we're at with this ticket, it was split into a couple of different chunks.

- PR#740 and PR#751 were merged to update the functionality for in-place registration for both pdarrayclass & Strings.
- Registration is now in-place.
- Registering an object multiple times with a different name will remove the old name and register the existing object with the new name.
- Trying to register more than one object with the same name will result in an Error
- Trying to register the same object using its existing name (i.e. re-registering it) will also trigger an error, you must first un-register the name and then re-register the name: This is due to the weak binding of objects between the client/server using a string name.  We have no idea if it's the same object trying to be registered.  (This may be something we want to work on in the future).

I am going to begin working on the register/unregister/attach functionality for GroupBy objects which will due an intro-spection and delegate the register calls to the internal objects.

**Comment by glitch** [comment]
@reuster986  Looking at GroupBy I found the following _internal_ pieces

- permutation [pdarray]
- segments [pdarray]
- unique_keys [list of [pdarray|Strings] ]
- unique_key_indices [pdarray]

Question 1: Do all of these pieces need to be registered? (the indices part was not included in one of the original comments)

Question 2: Does `self.keys` (which contains the original `keys` arg passed in via `__init__(..)` also need to be registered?

Also I think permutation can possibly be a Categorical object which currently doesn't support `register` so I think I'll also need to add that to the list.

Design note:
I was looking to inspect the vars of the GroupBy object and checking if they had a register method and then iteratively invoke that method on each piece so that GroupBy would dynamically handle registration of its parts, something like this:
```
vars_to_register = [(k, v) for k, v in vars(self).items() if hasattr(v, "register")]
for k, v in vars_to_register:
    v.register(f"{user_defined_name}_{k}")
```
However, based on the answers to the questions above there may be parts we need to ignore.  Also, if `self.keys` should be included then the above breaks down because we could have a list of the objects so I'd need to unpack that first and add some type of index component to the name.

**Comment by glitch** [comment]
UPDATE:  After discussion with @mhmerrill  we have decided to postpone the GroupBy registration implementation in favor of a Complex object impl on the server-side.

I believe this ticket can be closed.  (Or we can also wait until the resolution of #761)

**Comment by glitch** [comment]
Issue #761 was merged.  Closing ticket based on our discussion of postponing  GroupBy registration.
