### ISSUE TITLE
Create Registration List Function 

### ISSUE THREAD

**Issue by pierce314159** [mhmerrill/arkouda#734]
Related to issue #729 

Create a function to list all objects currently registered. This will be useful for testing the registration method and will enable users to easily see which objects are available to them after reconnecting to the server. I'll be working this issue with @glitch

**Comment by glitch** [comment]
Note: @pierce314159 did find the `SymbolTable.info("__AllSymbols__")` special arg, but the info returned doesn't contain any registration information.  We talked about the trade-offs of adding that registry info here or making a dedicated command / msg to do it.  In the end we feel adding a first-class command is probably better for the following reasons:

- Better visibility from a client perspective since it will be part of the client API
- Adding parsing/filtering code on the client side to split the registered items from everything else would be a little messy to maintain since there really isn't a formalized format to the info strings message.
- Less bytes on the wire and less iterations across a table.  The number of registry items should always be less than or equal to what is in the lookup table.

If folks have a strong feeling opposed to a new message command, please let us know and we could change the approach.

**Comment by mhmerrill** [comment]
@glitch @pierce314159 I want it added to the ak.info call

**Comment by pierce314159** [comment]
@mhmerrill sounds good! I also just noticed that `ak.info(ak.AllSymbols)` throws a `ValueError` if no objects have been created yet. Would it be fine for me to check if the symbol table is empty and return a message saying the table is empty or is the `ValueError` being used by something?

**Comment by mhmerrill** [comment]
> @mhmerrill sounds good! I also just noticed that `ak.info(ak.AllSymbols)` throws a `ValueError` if no objects have been created yet. Would it be fine for me to check if the symbol table is empty and return a message saying the table is empty or is the `ValueError` being used by something?

@pierce314159 
We should be catching this and returning this from the server... i hope the server does not crash ;-o
If the ST is empty maybe that is the right call to return an message which says the ST is empty.

**Comment by pierce314159** [comment]
The server isn't crashing! Just a error on the client side. I'll do a check and return a message if the ST is empty
